elasticsearchHosts: "http://elasticsearch-master:9200"
service:
  type: NodePort
replicas: 1
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

lifecycle:
  preInstall:
    enabled: false
  postInstall:
    enabled: false
  preUpgrade:
    enabled: false
  postUpgrade:
    enabled: false
  preDelete:
    enabled: false
  postDelete:
    enabled: false

elasticsearch:
  hosts: "http://elasticsearch-master:9200"
  ssl:
    verificationMode: none

extraEnvs:
  - name: ELASTICSEARCH_HOSTS
    value: "http://elasticsearch-master:9200"
  - name: ELASTICSEARCH_USERNAME
    value: ""
  - name: ELASTICSEARCH_PASSWORD
    value: ""
  - name: XPACK_SECURITY_ENABLED
    value: "false"